/**
 * Generate TOML configuration files for JDC and Translator
 * Based on sv2-apps/docker/config templates
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import type { SetupData } from './types.js';
const BRAIINS_POOL_AUTHORITY_KEY = '9awtMD5KQgvRUh2yFbjVeT7b6hjipWcAsQHd6wEhgtDT9soosna';
const BRAIINS_POOL_ADDRESS = 'stratum.braiins.com';

interface PortsConfig {
  TRANSLATOR_PORT: number;
  JDC_PORT: number;
  JDC_AUTHORITY_PUBLIC_KEY: string;
}

function loadPorts(): PortsConfig {
  const candidatePaths = [
    join(process.cwd(), 'shared/ports.json'),
    join(process.cwd(), '../shared/ports.json'),
    join(process.cwd(), '../../shared/ports.json'),
  ];

  for (const candidatePath of candidatePaths) {
    if (!existsSync(candidatePath)) {
      continue;
    }

    const data = readFileSync(candidatePath, 'utf-8');
    return JSON.parse(data) as PortsConfig;
  }

  throw new Error(`Unable to locate shared/ports.json from ${process.cwd()}`);
}

function escapeTomlString(value: string): string {
  return JSON.stringify(value).slice(1, -1);
}

const ports = loadPorts();
export const TRANSLATOR_PORT = ports.TRANSLATOR_PORT;
export const JDC_PORT = ports.JDC_PORT;
export const JDC_AUTHORITY_PUBLIC_KEY = ports.JDC_AUTHORITY_PUBLIC_KEY;

function shouldAggregateTranslatorChannels(data: SetupData): boolean {
  if (!data.pool) return false;

  return data.pool.authority_public_key === BRAIINS_POOL_AUTHORITY_KEY
    || data.pool.address.toLowerCase() === BRAIINS_POOL_ADDRESS;
}

export function normalizeSetupData(data: SetupData): SetupData {
  if (!data.translator) return data;

  return {
    ...data,
    translator: {
      ...data.translator,
      aggregate_channels: shouldAggregateTranslatorChannels(data),
    },
  };
}

/**
 * Generate Translator Proxy config (tproxy-config.toml)
 */
export function generateTranslatorConfig(data: SetupData): string {
  const normalizedData = normalizeSetupData(data);
  const { pool, translator, mode } = normalizedData;
  const isJdMode = mode === 'jd';
  
  if (!translator || (!isJdMode && !pool)) {
    throw new Error('Pool and translator configuration are required');
  }
  
  // If JD mode, translator connects to JDC container; otherwise directly to pool
  // Both containers are on sv2-network, so we can use the container name as hostname
  // (hostname resolution supported since sv2-apps PR #286)
  const upstreamAddress = isJdMode ? 'sv2-jdc' : pool!.address;
  const upstreamPort = isJdMode ? JDC_PORT : pool!.port;
  // When connecting to local JDC, we don't need authority key (using hardcoded keys)
  // When connecting to external pool, we need the pool's authority key
  const authorityPubkey = isJdMode
    ? JDC_AUTHORITY_PUBLIC_KEY
    : pool!.authority_public_key;

  // Min hashrate from user config (default 100 TH/s if not set)
  const minHashrate = translator.min_hashrate ? `${translator.min_hashrate}.0` : '100_000_000_000_000.0';
  // Shares per minute target
  const sharesPerMinute = '6.0';

  return `# Translator Proxy Configuration
# Generated by sv2-ui

# Local Mining Device Downstream Connection
downstream_address = "0.0.0.0"
downstream_port = ${TRANSLATOR_PORT}

# Version support
max_supported_version = 2
min_supported_version = 2

# Extranonce2 size for downstream connections
downstream_extranonce2_size = 4

# User identity/username for the upstream connection
user_identity = "${escapeTomlString(translator.user_identity)}"

# Aggregate channels: if true, all miners share one upstream channel
aggregate_channels = ${translator.aggregate_channels}

# Protocol extensions configuration
supported_extensions = []
required_extensions = []

# Monitoring HTTP server address
monitoring_address = "0.0.0.0:9092"
monitoring_cache_refresh_secs = 15

# Difficulty params
[downstream_difficulty_config]
min_individual_miner_hashrate = ${minHashrate}
shares_per_minute = ${sharesPerMinute}
enable_vardiff = true
job_keepalive_interval_secs = 60

[[upstreams]]
address = "${escapeTomlString(upstreamAddress)}"
port = ${upstreamPort}
authority_pubkey = "${escapeTomlString(authorityPubkey)}"
`;
}

/**
 * Generate JD Client config (jdc-config.toml)
 */
export function generateJdcConfig(data: SetupData): string | null {
  if (data.mode !== 'jd' || !data.jdc || !data.bitcoin) {
    return null;
  }

  const { pool, jdc, bitcoin } = data;
  const isSovereignSolo = data.miningMode === 'solo';
  const jdcSignature = isSovereignSolo ? (jdc.jdc_signature || jdc.user_identity) : jdc.jdc_signature;

  // Shares per minute and batch size
  const sharesPerMinute = '6.0';
  const shareBatchSize = '5';
  // Fee threshold and min interval for template provider
  const feeThreshold = '1000';
  const minInterval = '5';
  const upstreamsConfig = !isSovereignSolo && pool
    ? `# Upstream pool connection
[[upstreams]]
authority_pubkey = "${escapeTomlString(pool.authority_public_key)}"
pool_address = "${escapeTomlString(pool.address)}"
pool_port = ${pool.port}
jds_address = "${escapeTomlString(pool.address)}"
jds_port = 3334

`
    : `# No upstreams needed in solo mining mode.
upstreams = []

`;

  return `# JD Client Configuration
# Generated by sv2-ui

listening_address = "0.0.0.0:${JDC_PORT}"

# Version support
max_supported_version = 2
min_supported_version = 2

# Auth keys for downstream connections
authority_public_key = "${escapeTomlString(JDC_AUTHORITY_PUBLIC_KEY)}"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# User identity/username for the upstream connection
user_identity = "${escapeTomlString(jdc.user_identity)}"

# Shares configuration
shares_per_minute = ${sharesPerMinute}
share_batch_size = ${shareBatchSize}

# JDC mode: FULLTEMPLATE, COINBASEONLY, or SOLOMINING
mode = "${escapeTomlString(isSovereignSolo ? 'SOLOMINING' : 'FULLTEMPLATE')}"

# String to be added into the Coinbase scriptSig
jdc_signature = "${escapeTomlString(jdcSignature)}"

# Solo Mining config - coinbase output for sovereign or fallback solo mining
coinbase_reward_script = "addr(${escapeTomlString(jdc.coinbase_reward_address)})"

# Protocol Extensions
supported_extensions = []
required_extensions = []

# Monitoring HTTP server address
monitoring_address = "0.0.0.0:9091"
monitoring_cache_refresh_secs = 15

${upstreamsConfig}# Bitcoin Core IPC config
[template_provider_type.BitcoinCoreIpc]
network = "${escapeTomlString(bitcoin.network)}"
fee_threshold = ${feeThreshold}
min_interval = ${minInterval}
`;
}
